head_scripts:
  - /assets/css/custom.css

title: "Hao Chen"
name: "Hao Chen"
description: "GeoAI · Remote Sensing · Wildlife Monitoring · Spatial Data Science"
url: "https://utdhao.github.io"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

author:
  name: "Hao Chen"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Ph.D. Candidate in Geospatial Information Sciences at The University of Texas at Dallas"
  location: "Richardson, TX"
  email: "hao.chen2@utdallas.edu"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/hao-chen-5718282b6"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=BNp7wUYAAAAJ"

include:
  - _pages

plugins:
  - jekyll-include-cache
