title: "Hao Chen"
name: "Hao Chen"
description: "Geospatial Data Scientist | GeoAI | Remote Sensing | UTD"
url: "https://utdhao.github.io"
avatar: "/assets/images/bio-photo.jpg"

author:
  name: "Hao Chen"
  bio: "Ph.D. Candidate, Geospatial Information Sciences · UT Dallas"
  location: "Richardson, TX"
  email: "hao.chen2@utdallas.edu"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/hao-chen-5718282b6"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=BNp7wUYAAAAJ"
